Include LDAP reset in running the tests.
Since we know that the tests won't work if the LDAP is setup wrongly,
force a reset before each run. This doesn't address the issue of things
in the LDAP ending up out of sync as a result of previous tests, but
is a useful step in the right direction for now.

Change-Id: I7be5e0a4e3cd6001a913b1f7c37879e724c8b256

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,2 +1,8 @@
 #!/bin/sh
-exec nosetests -d $*
+python tests/reset_ldap.py
+if [ $? -ne 0 ]
+then
+	echo 'Failed to reset LDAP' $?
+else
+	exec nosetests -d $*
+fi
